### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by uahsan3** [sometimesfood/spact-matlab#1]
I have a question. Did you finish with this repo or was there something left? Because I saw some incomplete files. Do they mean anything?

Thanks

**Comment by sometimesfood** [comment]
The code is not in active use anymore, but it should be pretty much complete.

What do you mean by "incomplete files"?

**Comment by uahsan3** [comment]
There was a To-do file, which was empty.

**Comment by sometimesfood** [comment]
It's empty because I implemented everything on my To-do list:

https://github.com/sometimesfood/spact-matlab/commits/master/TODO.org

**Comment by uahsan3** [comment]
Sorry. I'm a beginner.

Got it. Thanks

**Comment by sometimesfood** [comment]
No problem at all, no harm done.
