### ISSUE TITLE
how run this code

### ISSUE THREAD

**Issue by haitaobiyao** [sometimesfood/spact-matlab#2]
I want know how run this code

**Comment by sometimesfood** [comment]
That depends on what you want to do. `searchgui` is probably the most reasonable entry point.

Having said that: I have not found CENTRIST to perform nearly as well as described in the CENTRIST paper, so personally I would not use this code (or any other CENTRIST implementation) at all.

There a lot of alternatives you could use instead, so if I were you I'd save myself the headache of getting CENTRIST to work and choose a better descriptor.
